name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
variables:
  phpVersion: '7.4'

jobs:
- job: Job_1
  displayName: Build artifact
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
    clean: true

  - script: ./bin/set_php_versions.sh ${{ variables.phpVersion }}
    workingDirectory: $(System.DefaultWorkingDirectory)/infrastucture
    displayName: 'PHP version'

  - script: cp infrastructure/conf/deploy.htaccess .htaccess
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: 'Write-out htaccess'

  - script: ./bin/deploy.sh $(System.DefaultWorkingDirectory)
    workingDirectory: $(System.DefaultWorkingDirectory)/infrastucture
    displayName: Dependencies
    env:
      API_URI: /graphql
      ADMIN_APP_DIR: /admin
      TALENTSEARCH_APP_DIR: /talent
      # We don't need Cypress in this environment, and so this avoid permission errors of installing it.
      # See: https://docs.cypress.io/guides/getting-started/installing-cypress#Skipping-installation
      CYPRESS_INSTALL_BINARY: 0

  - task: ArchiveFiles@2
    displayName: 'Archive $(System.DefaultWorkingDirectory)'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/Application_$(Build.BuildId).zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: gcDigitalTalent'
    inputs:
      ArtifactName: gcDigitalTalent
