name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      working-directory: api
      run: |
          cp .env.example .env
          composer install --prefer-dist
          php artisan migrate:fresh --seed
          php artisan lighthouse:print-schema --write

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: pgsql
        DB_DATABASE: gctalent
        DB_USERNAME: postgres
        DB_PASSWORD: password1234

      working-directory: api
      run: vendor/bin/phpunit
