name: Lint

on:
  push:
    branches: [ main ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    env:
      NPM_VERSION: "8.3.0"

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version-file: frontend/.nvmrc
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        run: npm install --global npm@${{ env.NPM_VERSION }}

      - name: "Install dependencies: workspace"
        working-directory: frontend
        run: npm install


      - name: "Run ESlint: common"
        working-directory: frontend/common
        continue-on-error: true
        run: |
          npm run codegen
          npm run lint

      - name: "Run ESlint: admin"
        working-directory: frontend/admin
        continue-on-error: true
        run: |
          npm run codegen
          npm run lint

      - name: "Run ESlint: talentSearch"
        working-directory: frontend/talentsearch
        continue-on-error: true
        run: |
          npm run codegen
          npm run lint
