name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install composer dependencies
        working-directory: api
        run: |
          cp .env.example .env
          composer install --prefer-dist

      - name: PHPUnit tests
        working-directory: api
        run: vendor/bin/phpunit
